name: System Automation Bash

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Ejecutar script bash
        run: |
          chmod +x ./scripts/script.sh
          ./scripts/script.sh
        env:
          CUSTOM_VAR: ${{ secrets.CUSTOM_VAR }}

      - name: Mostrar archivo generado
        run: cat output.txt

      - name: Subir artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-bash
          path: output.txt
